sudo: true
dist: xenial
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
matrix:
  include:
      - python: 3.4
        env: TOX_ENV=py34
      - python: 3.5
        env: TOX_ENV=py35
      - python: 3.6
        env: TOX_ENV=py36
      - python: 3.7
        env: TOX_ENV=py37
      - python: pypy3
        env: TOX_ENV=pypy3
  
  allow_failures:
    - python: "pypy3"

install:
  - pip install .
  - pip install codecov tox

script:
  - tox -e $TOX_ENV,speed -v 2
  - |
    if [ $TOX_ENV == "py37" ]; then
      tox -e coverage_unittest,codechecks
    fi

after_success:
  - codecov
  
notifications:
  email: false
