sudo: false
dist: xenial
language: python
cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log
matrix:
  include:
      - python: 2.7
        env: ENV=py27
      - python: 3.4
        env: ENV=py34
      - python: 3.5
        env: ENV=py35
      - python: 3.6
        env: ENV=py36
      - python: 3.7
        env: ENV=py37
        dist: xenial
        sudo: true
      - python: pypy
        env: ENV=pypy
      - python: pypy3
        env: ENV=pypy3
  
  allow_failures:
    - python: "pypy3"
    - python: "pypy"

install:
  # - pip list
  # - if [[ -e build-requirements-${TRAVIS_PYTHON_VERSION}.txt ]]; then travis_retry pip install -r build-requirements-${TRAVIS_PYTHON_VERSION}.txt; else travis_retry pip install -r build-requirements.txt; fi
  # - pip list
  - python setup.py install
  - pip install codecov

script:
  # - tox -e $ENV
  # - tox -e speed
  - cd test
  - coverage run test.py

after_success:
  - codecov

